### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'ï»¿555'

### ISSUE THREAD

**Issue by Adnan-annan** [SakuraRiven/EAST#22]
C:\Users\Adnan\AppData\Local\Programs\Python\Python35\python.exe C:/Users/Adnan/EAST/train.py
C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\optim\lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "C:/Users/Adnan/EAST/train.py", line 66, in <module>
    train(train_img_path, train_gt_path, pths_path, batch_size, lr, num_workers, epoch_iter, save_interval)	
  File "C:/Users/Adnan/EAST/train.py", line 35, in train
    for i, (img, gt_score, gt_geo, ignored_map) in enumerate(train_loader):
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Adnan\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Adnan\EAST\dataset.py", line 385, in __getitem__
    vertices, labels = extract_vertices(lines)
  File "C:\Users\Adnan\EAST\dataset.py", line 365, in extract_vertices
    vertices.append(list(map(int, line.rstrip('\n').lstrip('\ufeff').split(',')[:8])))
ValueError: invalid literal for int() with base 10: 'ï»¿555'

**Comment by Adnan-annan** [comment]
kindly help me solve this issue, while reading annotations from txt file i get this error, i am helpless how to solve this problem.

**Comment by Adnan-annan** [comment]
change the code in dataset.py to with open(self.gt_files[index], 'r',encoding="utf-8") as f:
it solves the problem
