### ISSUE TITLE
请帮忙看看，测试不了是什么情况

### ISSUE THREAD

**Issue by Primarysf** [SakuraRiven/EAST#57]

**Comment by Primarysf** [comment]
/bin/sh: 1: zip: not found
mv: cannot stat 'submit.zip': No such file or directory
/bin/sh: 1: python: not found
Traceback (most recent call last):
  File "/workspace/EAST/eval.py", line 43, in <module>
    eval_model(model_name, test_img_path, submit_path)
  File "/workspace/EAST/eval.py", line 32, in eval_model
    os.remove('submit.zip')
FileNotFoundError: [Errno 2] No such file or directory: 'submit.zip'

进程已结束，退出代码为 1

**Comment by lzltommy0805** [comment]
解决了吗？
