### ISSUE TITLE
执行python train.py 遇到以下问题。望回复

### ISSUE THREAD

**Issue by tony8888lrz** [SakuraRiven/EAST#58]
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    train(train_img_path, train_gt_path, pths_path, batch_size, lr, num_workers, epoch_iter, save_interval)
  File "train.py", line 38, in train
    pred_score, pred_geo = model(img)
  File "C:\Users\Tony\anaconda3\envs\EAST\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Tony\PycharmProjects\EAST\model.py", line 168, in forward
    return self.output(self.merge(self.extractor(x)))
  File "C:\Users\Tony\anaconda3\envs\EAST\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Tony\PycharmProjects\EAST\model.py", line 73, in forward
    x = m(x)
  File "C:\Users\Tony\anaconda3\envs\EAST\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Tony\anaconda3\envs\EAST\lib\site-packages\torch\nn\modules\batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "C:\Users\Tony\anaconda3\envs\EAST\lib\site-packages\torch\nn\functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 6.00 GiB total capacity; 4.64 GiB already allocated; 0 bytes free; 516.50 KiB cached)

**Comment by fangzhou-ye** [comment]
感觉这种问题一般把batch size调小一些就可以
